Config guide
MapColonies/infra-portal pull request #7
Opened 2024-09-02 10:42 UTC by CptSchnitz

2024-09-04 08:59 UTC, netanelC requested changes
Great Work!

2024-09-04 08:59 UTC, netanelC commented on docs/ConfigManagement/zero-to-hero.mdx
> +
Add a flow (using mermaid or similar tool) that visulizes the integration between all the components

2024-09-04 08:59 UTC, netanelC commented on docs/ConfigManagement/zero-to-hero.mdx
> +## Initialize the work environment
Before diving into the practical instuctions, consider writing a use case or mitivation why one should use this system

2024-09-04 08:59 UTC, netanelC commented on docs/ConfigManagement/zero-to-hero.mdx
> +3. If we want our service schema to extends the base boilerplate schema we could do this like that:
typo
```suggestion
3. If we want our service schema to extend the base boilerplate schema we could do this like that:
```

2024-09-04 10:27 UTC, CptSchnitz commented on docs/ConfigManagement/zero-to-hero.mdx
> +## Initialize the work environment
is it really the place for this?

2024-09-04 10:29 UTC, CptSchnitz commented on docs/ConfigManagement/zero-to-hero.mdx
> +
i will add, but also not sure if this is the place, we might need a landing page for the config management

2024-09-04 12:18 UTC, netanelC commented on docs/ConfigManagement/zero-to-hero.mdx
> +
Agreed, I will add an issue about that

2024-09-04 12:20 UTC, netanelC commented on docs/ConfigManagement/zero-to-hero.mdx
> +## Initialize the work environment
I'll create an issue for the landing page but for now add this here

2024-09-12 07:28 UTC, netanelC requested changes
Add an example of using "allOf" with deep objects

2024-09-12 12:15 UTC, RonitKissis commented on docs/ConfigManagement/zero-to-hero.mdx
> +You want to use the MapColonies™ Config Management system in your service to manage all the configurations in one place.
good work on the trademark

2024-09-12 12:20 UTC, RonitKissis commented on docs/ConfigManagement/zero-to-hero.mdx
> +
after the motivation section and before the dive in, consider pointing out the stages in general : creating a schema -> validation -> implementation in the service. Just so that the developer would know what to expect

2024-09-15 10:35 UTC, netanelC approved these changes

2024-10-05 04:35 UTC, merged